### ISSUE TITLE
getData function not working

### ISSUE THREAD

**Issue by seandres11** [rspatial/raster#191]
Hi!

I am having issues downloading worldclim data through the raster package. 

See code below for error message, and let me know if I can provide any other information to help!

r<-getData('CMIP5', var='bio', res=2.5, rcp=85, model="CN" , year=70, lon=151.0034, lat=-33.8136, download=TRUE)
trying URL 'https://biogeo.ucdavis.edu/data/climate/cmip5/2_5m/cn85bi70.zip'
Content type 'application/zip' length 183455516 bytes (175.0 MB)
==
downloaded 8.1 MB

Error in utils::download.file(url = aurl, destfile = fn, method = "auto",  : 
  download from 'https://biogeo.ucdavis.edu/data/climate/cmip5/2_5m/cn85bi70.zip' failed
In addition: Warning messages:
1: In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  downloaded length 8454144 != reported length 183455516
2: In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  URL 'https://data.biogeo.ucdavis.edu/data/climate/cmip5/2_5m/cn85bi70.zip': Timeout of 60 seconds was reached

**Comment by rhijmans** [comment]
This works for me, so this was probably a temporary glitch (the webserver not working well).

**Comment by KaraLayton** [comment]
I'm having this same problem now, but haven't had this problem in the past. Just wondering if this is a server issue or if there's another way to fix this? Thanks!

**Comment by seandres11** [comment]
Hey!

Are you on a mac??

I fixed my issue by changing my cran mirror to Mac. Theres also a new version of r now which updating might also help.

https://cran.r-project.org/bin/macosx/

Let me know if that helps!

Cheers,
Sam

Sent via the Samsung Galaxy S9, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KaraLayton** [comment]
Thanks Sam! I tried installing the newest version of R and still having the issue. If you don't mind me asking, which mirror are you using? I don't see an option for a Mac mirror specifically.

**Comment by seandres11** [comment]
Hmm, are you on a mac?

At the moment, I am using the CDN Global mirror. Perhaps the function you are using is masked by another package?

Cheers,
Sam

Samantha E. Andres
Plant Ecologist and PhD Candidate
Hawkesbury Institute for the Environment
+61 (435)-411-549
WSU Postgraduate Page<https://www.westernsydney.edu.au/hie/people/postgraduate_students/current_postgraduate_students/samantha_andres>


________________________________

**Comment by rlfrench** [comment]
I've been encountering the same issue for the past two days. Like others who have posted in this thread, I've used the getData function many times (most recently in March) and have never encountered this problem before!

Each time, I've tried running getData as follows:

`bioclimdat <- raster::getData(name = "worldclim",
                      var = "bio",
                      res = 2.5)`

and every time, I get this message (although the size of the "downloaded" file has ranged from 89.5 - 109.3 MB across my 5 or 6 unsuccessful attempts):

```
trying URL 'https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_2-5m_bil.zip'
Content type 'application/zip' length 129319755 bytes (123.3 MB)
====================================
downloaded 89.5 MB

Error in utils::download.file(url = aurl, destfile = fn, method = "auto",  : 
  download from 'https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_2-5m_bil.zip' failed
In addition: Warning messages:
1: In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  downloaded length 93880320 != reported length 129319755
2: In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  URL 'https://data.biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_2-5m_bil.zip': Timeout of 60 seconds was reached
```

I have access to .bil and .hdr files for each of the 19 bioclimatic variables from my last successful getData run in March. Is there a way of using those files to create a raster stack while the webserver is down/malfunctioning (if that is the source of the issue)?

**Comment by rhijmans** [comment]
Hi @marcoplebani85  
The error message `Peer certificate cannot be authenticated with given CA certificates'  would seem to be related to your system. What are you using (OS, R version)?
Can you try on another computer?
To create a RasterStack from the files, you can do 
`stack(filenames)`

**Comment by marcoplebani85** [comment]
Hello,
```
sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.5
```
I don't think their server is the issue because I can download the data by opening the link that getData can't access using my browser. Good to know about `stack()`, thanks. I managed to use getData() to access local files by downloading them, "unfoldering" them, putting them in a new folder called "wc0.5" in my work directory, and setting `download=F` in `getData()`. Cheers!
